services:
    ### PostgreSQL Database (Stores Airflow metadata + App Data) ###
    postgres:
        image: postgres:13
        container_name: postgres
        restart: always
        environment:
        - POSTGRES_USER=postgres_admin
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - AIRFLOW_DB_PASSWORD=${AIRFLOW_DB_PASSWORD}
        - APP_DB_PASSWORD=${APP_DB_PASSWORD}
        ports:
          - "5432:5432"
        volumes:
          - ./database/postgres_data:/var/lib/postgresql/data
          - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql  # Use SQL instead of Bash

    ### Airflow Webserver (UI for DAG management) ###
    airflow-webserver:
        image: apache/airflow:2.6.3
        container_name: airflow_webserver
        restart: always
        depends_on:
        - postgres
        environment:
        - AIRFLOW__CORE__EXECUTOR=LocalExecutor
        - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow_user:${AIRFLOW_DB_PASSWORD}@postgres/airflow_db
        - AIRFLOW_CONN_APP_DB=postgresql://airflow_user:${AIRFLOW_DB_PASSWORD}@postgres:5432/app_db
        - AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE=UTC
        volumes:
        - ./airflow/dags:/opt/airflow/dags
        - ./airflow/logs:/opt/airflow/logs
        - ./airflow/config:/opt/airflow/config
        - ./airflow/data:/opt/airflow/data  # Mounted transcript and audio storage
        ports:
        - "8080:8080"
        command: webserver

    ### Airflow Scheduler (Executes DAGs) ###
    airflow-scheduler:
        image: apache/airflow:2.6.3
        container_name: airflow_scheduler
        restart: always
        depends_on:
        - postgres
        environment:
        - AIRFLOW__CORE__EXECUTOR=LocalExecutor
        - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow_user:${AIRFLOW_DB_PASSWORD}@postgres/airflow_db
        - AIRFLOW_CONN_APP_DB=postgresql://airflow_user:${AIRFLOW_DB_PASSWORD}@postgres:5432/app_db
        volumes:
        - ./airflow/dags:/opt/airflow/dags
        - ./airflow/logs:/opt/airflow/logs
        - ./airflow/config:/opt/airflow/config
        - ./airflow/data:/opt/airflow/data  # Mounted transcript and audio storage
        command: scheduler

    ### Airflow Init (Bootstraps the environment) ###
    airflow-init:
        image: apache/airflow:2.6.3
        container_name: airflow_init
        depends_on:
        - postgres
        environment:
        - AIRFLOW__CORE__EXECUTOR=LocalExecutor
        - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow_user:${AIRFLOW_DB_PASSWORD}@postgres/airflow_db
        - AIRFLOW_CONN_APP_DB=postgresql://airflow_user:${AIRFLOW_DB_PASSWORD}@postgres:5432/app_db
        entrypoint: ["airflow", "db", "init"]

